# Generated by Django 5.1.4 on 2025-04-07 20:06

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0037_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('theater_cms', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorLogo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(help_text='Sponsor name for alt text and accessibility', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Optional link to sponsor website')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_logos', to=settings.FILER_IMAGE_MODEL, verbose_name='Sponsor Logo')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
