# Generated by Django 5.1.4 on 2025-04-07 20:56

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
        ('theater_cms', '0002_sponsorlogo'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCard',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(help_text="Event title (e.g., 'Tosca')", max_length=200)),
                ('composer', models.CharField(help_text="Composer name (e.g., 'Giacomo Puccini')", max_length=200)),
                ('date_range', models.CharField(help_text="Performance dates (e.g., 'January 15 - March 30, 2024')", max_length=200)),
                ('detail_url', models.URLField(blank=True, help_text='Optional link to event detail page')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to=settings.FILER_IMAGE_MODEL, verbose_name='Event Image')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
