# Generated by Django 5.1.4 on 2025-04-19 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_auto_20240311_1028'),
        ('theater_cms', '0005_emailsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAItemPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(help_text='You may use HTML for formatting', verbose_name='Answer')),
            ],
            bases=('cms.cmsplugin',),
        ),
    ]
