# Generated by Django 5.1.4 on 2025-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0006_qaitemplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('composer', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('date_range_display', models.CharField(blank=True, help_text="Display text for date range (e.g., 'January 15 - March 20, 2024')", max_length=200)),
                ('about_content', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=200)),
                ('conductor', models.CharField(blank=True, max_length=200)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('cast_content', models.TextField(blank=True)),
                ('additional_details', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'start_datetime'],
            },
        ),
    ]
