# Generated by Django 5.1.4 on 2025-04-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0007_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['sort_order', 'start_datetime'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='standard_duration',
            field=models.DurationField(blank=True, help_text="Standard duration of a performance (e.g., '02:30:00' for 2.5 hours)", null=True, verbose_name='Standard Duration'),
        ),
        migrations.AlterField(
            model_name='event',
            name='about_content',
            field=models.TextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='event',
            name='additional_details',
            field=models.TextField(blank=True, verbose_name='Additional Details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cast_content',
            field=models.TextField(blank=True, verbose_name='Cast'),
        ),
        migrations.AlterField(
            model_name='event',
            name='composer',
            field=models.CharField(max_length=200, verbose_name='Composer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conductor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Conductor'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_range_display',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='Date Range'),
        ),
        migrations.AlterField(
            model_name='event',
            name='director',
            field=models.CharField(blank=True, max_length=200, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=200, verbose_name='Duration Display Text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Performance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Event Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, max_length=200, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='First Performance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('is_special', models.BooleanField(default=False, help_text='Mark for premieres, galas, or special events', verbose_name='Special Performance')),
                ('notes', models.CharField(blank=True, help_text="Special notes for this performance (e.g., 'Premiere', 'With English subtitles')", max_length=255, verbose_name='Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='theater_cms.event')),
            ],
            options={
                'verbose_name': 'Performance',
                'verbose_name_plural': 'Performances',
                'ordering': ['start_time'],
            },
        ),
    ]
