# Generated by Django 5.1.4 on 2025-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0008_alter_event_options_event_standard_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_sponsors/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='seasonal_sponsors/')),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='performance',
            name='is_special',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='notes',
        ),
        migrations.AddField(
            model_name='event',
            name='sponsors_images',
            field=models.ManyToManyField(blank=True, related_name='events', to='theater_cms.eventsponsorimage', verbose_name='Event-Specific Sponsors'),
        ),
    ]
