# Generated by Django 5.1.4 on 2025-04-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0009_eventsponsorimage_seasonalsponsor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sponsors_images',
        ),
        migrations.AddField(
            model_name='eventsponsorimage',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_images', to='theater_cms.event', verbose_name='Event'),
        ),
    ]
