# Generated by Django 5.1.4 on 2025-04-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0010_remove_event_sponsors_images_eventsponsorimage_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_height', models.IntegerField(choices=[(800, '800px (Full Size)'), (400, '400px (Compact)')], default=800, help_text='Select the display height for all theater screens.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
