# Generated by Django 5.1.4 on 2025-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0011_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='display_height',
            field=models.IntegerField(choices=[(800, '1280 × 800px (Full Size)'), (400, '1280 × 400px (Compact)'), (600, '1024 × 600px (Medium)')], default=800, help_text='Select the display height for all theater screens.'),
        ),
    ]
