# Generated by Django 5.1.4 on 2025-05-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0013_alter_userfeedback_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsponsorimage',
            name='website',
        ),
        migrations.RemoveField(
            model_name='seasonalsponsor',
            name='website',
        ),
        migrations.RemoveField(
            model_name='sponsorlogo',
            name='website',
        ),
    ]
