# Generated by Django 5.1.4 on 2025-05-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0014_remove_eventsponsorimage_website_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
