# Generated by Django 5.1.4 on 2025-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0015_remove_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_content_zh',
            field=models.TextField(blank=True, help_text='Chinese translation of the about content', verbose_name='About Content (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cast_content_zh',
            field=models.TextField(blank=True, help_text='Chinese translation of cast information', verbose_name='Cast Content (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='composer_zh',
            field=models.CharField(blank=True, help_text='Chinese translation of composer name', max_length=100, verbose_name='Composer (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='conductor_zh',
            field=models.CharField(blank=True, help_text='Chinese translation of conductor name', max_length=100, verbose_name='Conductor (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='director_zh',
            field=models.CharField(blank=True, help_text='Chinese translation of director name', max_length=100, verbose_name='Director (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_zh',
            field=models.CharField(blank=True, help_text="e.g., '约3小时（含休息时间）'", max_length=50, verbose_name='Duration (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='language_zh',
            field=models.CharField(blank=True, help_text="e.g., '意大利语配中文字幕'", max_length=100, verbose_name='Language (Chinese)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_zh',
            field=models.CharField(blank=True, help_text='Chinese translation of the event title', max_length=200, verbose_name='Title (Chinese)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='about_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='cast_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='composer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='conductor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_range_display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='director',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='standard_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='qaitemplugin',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
