# Generated by Django 5.1.4 on 2025-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0016_event_about_content_zh_event_cast_content_zh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Esteemed Sponsors', help_text='Main title displayed on the sponsors page', max_length=200, verbose_name='Page Title (English)')),
                ('intro_text', models.TextField(default='Our theater is proud to acknowledge the generous support of our sponsors. Their commitment to the arts enables us to continue our tradition of excellence and share the magic of opera with audiences from around the world.', help_text='Introduction text displayed below the title', verbose_name='Introduction Text (English)')),
                ('title_ru', models.CharField(default='Наши уважаемые спонсоры', help_text='Main title displayed on the Russian sponsors page', max_length=200, verbose_name='Page Title (Russian)')),
                ('intro_text_ru', models.TextField(default='Наш театр с гордостью благодарит спонсоров за их щедрую поддержку. Их приверженность искусству позволяет нам продолжать традиции совершенства и делиться магией оперы с аудиторией со всего мира.', help_text='Introduction text displayed below the title on Russian page', verbose_name='Introduction Text (Russian)')),
            ],
            options={
                'verbose_name': 'Sponsor Page Content',
                'verbose_name_plural': 'Sponsor Page Content',
            },
        ),
    ]
