# Generated by Django 5.1.4 on 2025-06-20 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0016_event_about_content_zh_event_cast_content_zh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], help_text='Language for this content set', max_length=2, unique=True)),
                ('sponsors_title', models.CharField(default='Our Esteemed Sponsors', help_text='Main title displayed at the top of the sponsors page', max_length=200)),
                ('sponsors_intro', models.TextField(default='Our theater is proud to acknowledge the generous support of our sponsors. Their commitment to the arts enables us to continue our tradition of excellence and share the magic of opera with audiences from around the world.', help_text="Introduction text explaining the theater's relationship with sponsors")),
                ('seasonal_sponsors_label', models.CharField(default='Seasonal Sponsors', help_text='Label for the seasonal sponsors section', max_length=100)),
                ('event_sponsors_label_template', models.CharField(default='{event_title} Sponsors', help_text='Template for event-specific sponsors label. Use {event_title} as placeholder.', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsors Page Content',
                'verbose_name_plural': 'Sponsors Page Content',
                'ordering': ['language'],
            },
        ),
    ]
