# Generated by Django 5.1.4 on 2025-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0017_sponsorpagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='about_content_zh',
            field=models.TextField(blank=True, help_text='Russian translation of the about content', verbose_name='About Content (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cast_content_zh',
            field=models.TextField(blank=True, help_text='Russian translation of cast information', verbose_name='Cast Content (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='composer_zh',
            field=models.CharField(blank=True, help_text='Russian translation of composer name', max_length=100, verbose_name='Composer (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='conductor_zh',
            field=models.CharField(blank=True, help_text='Russian translation of conductor name', max_length=100, verbose_name='Conductor (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='director_zh',
            field=models.CharField(blank=True, help_text='Russian translation of director name', max_length=100, verbose_name='Director (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration_zh',
            field=models.CharField(blank=True, help_text="e.g., 'Около 3 часов (включая антракт)'", max_length=50, verbose_name='Duration (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='language_zh',
            field=models.CharField(blank=True, help_text="e.g., 'На итальянском языке с русскими субтитрами'", max_length=100, verbose_name='Language (Russian)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_zh',
            field=models.CharField(blank=True, help_text='Russian translation of the event title', max_length=200, verbose_name='Title (Russian)'),
        ),
    ]
