# Generated by Django 5.1.4 on 2025-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0017_sponsorspagecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorspagecontent',
            options={'verbose_name': 'Sponsors Page Content', 'verbose_name_plural': 'Sponsors Page Content'},
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='event_sponsors_label_template',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='language',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='seasonal_sponsors_label',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_intro',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_title',
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_en',
            field=models.TextField(default='Our theater is proud to acknowledge the generous support of our sponsors. Their commitment to the arts enables us to continue our tradition of excellence and share the magic of opera with audiences from around the world.', help_text="Introduction text explaining the theater's relationship with sponsors", verbose_name='Sponsors Introduction (English)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_zh',
            field=models.TextField(default='我们剧院自豪地感谢赞助商的慷慨支持。他们对艺术的承诺使我们能够延续卓越传统，并与来自世界各地的观众分享歌剧的魅力。', help_text='Introduction text for Chinese sponsors page', verbose_name='Sponsors Introduction (Chinese)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_title_en',
            field=models.CharField(default='Our Esteemed Sponsors', help_text='Main title displayed at the top of the sponsors page', max_length=200, verbose_name='Sponsors Title (English)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_title_zh',
            field=models.CharField(default='我们尊贵的赞助商', help_text='Main title displayed at the top of the Chinese sponsors page', max_length=200, verbose_name='Sponsors Title (Chinese)'),
        ),
    ]
