# Generated by Django 5.1.4 on 2025-08-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0018_alter_sponsorspagecontent_options_and_more'),
    ]

    operations = [
    ]
