# Generated by Django 5.1.4 on 2025-07-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0018_alter_event_about_content_zh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about_content_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cast_content_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='composer_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conductor_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='director_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='language_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_zh',
        ),
        migrations.RemoveField(
            model_name='sponsorpagecontent',
            name='intro_text_ru',
        ),
        migrations.RemoveField(
            model_name='sponsorpagecontent',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='event',
            name='about_content_lt',
            field=models.TextField(blank=True, help_text='Renginio aprašymo lietuviškas vertimas', verbose_name='Aprašymas (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cast_content_lt',
            field=models.TextField(blank=True, help_text='Atlikėjų informacijos lietuviškas vertimas', verbose_name='Atlikėjų informacija (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='composer_lt',
            field=models.CharField(blank=True, help_text='Kompozitoriaus vardo lietuviškas vertimas', max_length=100, verbose_name='Kompozitorius (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='conductor_lt',
            field=models.CharField(blank=True, help_text='Dirigento vardo lietuviškas vertimas', max_length=100, verbose_name='Dirigentas (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='director_lt',
            field=models.CharField(blank=True, help_text='Režisieriaus vardo lietuviškas vertimas', max_length=100, verbose_name='Režisierius (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_lt',
            field=models.CharField(blank=True, help_text="pvz., 'Apie 3 valandas (su pertrauka)'", max_length=50, verbose_name='Trukmė (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='language_lt',
            field=models.CharField(blank=True, help_text="pvz., 'Italų kalba su lietuviškais subtitrais'", max_length=100, verbose_name='Kalba (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_lt',
            field=models.CharField(blank=True, help_text='Renginio pavadinimo lietuviškas vertimas', max_length=200, verbose_name='Pavadinimas (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='sponsorpagecontent',
            name='intro_text_lt',
            field=models.TextField(default='Mūsų teatras didžiuojasi pripažindamas savo rėmėjų dosnų palaikymą. Jų atsidavimas menams leidžia mums tęsti tobulumo tradicijas ir dalytis operos magija su žiūrovais iš viso pasaulio.', help_text='Įžangos tekstas, rodomas po pavadinimu lietuvių puslapyje', verbose_name='Įžangos tekstas (lietuviškai)'),
        ),
        migrations.AddField(
            model_name='sponsorpagecontent',
            name='title_lt',
            field=models.CharField(default='Mūsų gerbiami rėmėjai', help_text='Pagrindinis pavadinimas, rodomas lietuviškame rėmėjų puslapyje', max_length=200, verbose_name='Puslapio pavadinimas (lietuviškai)'),
        ),
    ]
