# Generated by Django 5.1.4 on 2025-10-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0019_fix_sponsor_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about_content_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cast_content_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='composer_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conductor_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='director_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='language_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_zh',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_zh',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_title_zh',
        ),
        migrations.AddField(
            model_name='event',
            name='about_content_ar',
            field=models.TextField(blank=True, help_text='Arabic translation of the about content', verbose_name='About Content (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cast_content_ar',
            field=models.TextField(blank=True, help_text='Arabic translation of cast information', verbose_name='Cast Content (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='composer_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of composer name', max_length=100, verbose_name='Composer (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='conductor_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of conductor name', max_length=100, verbose_name='Conductor (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='director_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of director name', max_length=100, verbose_name='Director (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_ar',
            field=models.CharField(blank=True, help_text="e.g., 'حوالي 3 ساعات (مع الاستراحة)'", max_length=50, verbose_name='Duration (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='language_ar',
            field=models.CharField(blank=True, help_text="e.g., 'العرض باللغة الأصلية مع ترجمة عربية'", max_length=100, verbose_name='Language (Arabic)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of the event title', max_length=200, verbose_name='Title (Arabic)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_ar',
            field=models.TextField(default='يفتخر مسرحنا بالاعتراف بالدعم السخي من رعاتنا. التزامهم بالفنون يمكننا من مواصلة تقليد التميز ومشاركة سحر الأوبرا مع الجماهير من جميع أنحاء العالم.', help_text='Introduction text for Arabic sponsors page', verbose_name='Sponsors Introduction (Arabic)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_title_ar',
            field=models.CharField(default='رعاتنا المحترمون', help_text='Main title displayed at the top of the Arabic sponsors page', max_length=200, verbose_name='Sponsors Title (Arabic)'),
        ),
    ]
