# Generated by Django 5.1.4 on 2025-09-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0019_fix_sponsor_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about_content_lt',
            field=models.TextField(blank=True, help_text='Lithuanian translation of the about content', verbose_name='About Content (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cast_content_lt',
            field=models.TextField(blank=True, help_text='Lithuanian translation of cast information', verbose_name='Cast Content (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='composer_lt',
            field=models.CharField(blank=True, help_text='Lithuanian translation of composer name', max_length=100, verbose_name='Composer (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='conductor_lt',
            field=models.CharField(blank=True, help_text='Lithuanian translation of conductor name', max_length=100, verbose_name='Conductor (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='director_lt',
            field=models.CharField(blank=True, help_text='Lithuanian translation of director name', max_length=100, verbose_name='Director (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_lt',
            field=models.CharField(blank=True, help_text="e.g., 'apie 3 valandas (su pertrauka)'", max_length=50, verbose_name='Duration (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='language_lt',
            field=models.CharField(blank=True, help_text="e.g., 'italų kalba su lietuviškais subtitrais'", max_length=100, verbose_name='Language (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_lt',
            field=models.CharField(blank=True, help_text='Lithuanian translation of the event title', max_length=200, verbose_name='Title (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_lt',
            field=models.TextField(default='Mūsų teatras didžiuojasi dėkodamas rėmėjams už jų dosnų palaikymą. Jų atsidavimas menui leidžia mums tęsti puikumo tradiciją ir dalintis operos grožiu su žiūrovais iš viso pasaulio.', help_text='Introduction text for Lithuanian sponsors page', verbose_name='Sponsors Introduction (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_title_lt',
            field=models.CharField(default='Mūsų gerbiami rėmėjai', help_text='Main title displayed at the top of the Lithuanian sponsors page', max_length=200, verbose_name='Sponsors Title (Lithuanian)'),
        ),
    ]
