# Generated by Django 5.1.4 on 2025-09-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0020_add_lithuanian_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about_content_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cast_content_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='composer_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conductor_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='director_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='language_zh',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_zh',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_zh',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_title_zh',
        ),
    ]
