# Generated by Django 5.1.4 on 2025-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_cms', '0021_remove_event_about_content_zh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='about_content_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cast_content_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='composer_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conductor_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='director_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='language_lt',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title_lt',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_lt',
        ),
        migrations.RemoveField(
            model_name='sponsorspagecontent',
            name='sponsors_title_lt',
        ),
        migrations.AddField(
            model_name='event',
            name='about_content_ru',
            field=models.TextField(blank=True, help_text='Russian translation of the about content', verbose_name='About Content (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cast_content_ru',
            field=models.TextField(blank=True, help_text='Russian translation of cast information', verbose_name='Cast Content (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='composer_ru',
            field=models.CharField(blank=True, help_text='Russian translation of composer name', max_length=100, verbose_name='Composer (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='conductor_ru',
            field=models.CharField(blank=True, help_text='Russian translation of conductor name', max_length=100, verbose_name='Conductor (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='director_ru',
            field=models.CharField(blank=True, help_text='Russian translation of director name', max_length=100, verbose_name='Director (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_ru',
            field=models.CharField(blank=True, help_text="e.g., 'около 3 часов (включая антракты)'", max_length=50, verbose_name='Duration (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='language_ru',
            field=models.CharField(blank=True, help_text="e.g., 'на оригинальном языке с русскими субтитрами'", max_length=100, verbose_name='Language (Russian)'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(blank=True, help_text='Russian translation of the event title', max_length=200, verbose_name='Title (Russian)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_intro_ru',
            field=models.TextField(default='Наш театр с гордостью выражает благодарность нашим спонсорам за их щедрую поддержку. Их преданность искусству позволяет нам продолжать традицию совершенства и делиться волшебством оперы со зрителями со всего мира.', help_text='Introduction text for Russian sponsors page', verbose_name='Sponsors Introduction (Russian)'),
        ),
        migrations.AddField(
            model_name='sponsorspagecontent',
            name='sponsors_title_ru',
            field=models.CharField(default='Наши уважаемые спонсоры', help_text='Main title displayed at the top of the Russian sponsors page', max_length=200, verbose_name='Sponsors Title (Russian)'),
        ),
    ]
