# Generated by Django 5.1.4 on 2025-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('merchandise', 'Merchandise')], max_length=20),
        ),
    ]
